import { NextPage } from 'next'
import Head from 'next/head'
import { Card, Footer, Hero, NavBar, Products } from '@/components'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>motty93 web site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        //*<NavBar />
      }
      <Hero />
      <Products />
      <Footer />
    </>
  )
}

export default Home
